#!/usr/bin/env node
var cloudpub = undefined;
// Fix console to look like logger
console.info = console.debug = console.warn = console.error = console.log

try {
    cloudpub = require('./index.js');
} catch( ex ) {
    console.error("cloudpub not installed");
    process.exit(1);
}

var log = cloudpub.main.log;

log.level = 2
log.options.notime = true

cloudpub.main.init( false, function(err, server) {
    if(err) {
        log.stderr("Error: " + err.message);
        process.exit(1);
    };
    cloudpub.cloudfu.kya( process.argv.slice(2), process.env, function(err, background) {
        if(err) {
            log.stderr("Error: " + err.message);
            process.exit(1);
        };
        if(!background)
            process.exit(0);
    });
});
