#!/usr/bin/env node
var cloudpub = undefined;

try {
    cloudpub = require('./index.js');
} catch( ex ) {
    console.error(ex.message, ex.stack );
    process.exit(1);
}

var log = cloudpub.log;

log.options.notime = true

cloudpub.init( false, function(err, server) {
    if(err) {
        log.stderr("Error: " + err.message);
        process.exit(1);
    };
    cloudpub.cloudfu.kya( process.argv.slice(2), function(err, background) {
        if(err) {
            log.stderr("Error: " + err.message);
            cloudpub.stop();
        };
        if(!background) {
            cloudpub.stop();
        }
    });
});
