#!/usr/bin/env node
require('coffee-script');
var settings = require('./settings');
var main = require('./main');

main.init( function(err, server) {
    if(err) {
        settings.log.fatal( "Fatal error: " + err.message );
        main.stop();
        process.exit(1);
    } else {
        server.on('error', function(err) {
            settings.log.fatal( "Fatal error: " + err.message );
            main.stop();
            process.exit(1);
        });
        settings.log.info("Server started on " + settings.HOST + ":" + settings.PORT );
        server.listen( settings.PORT );
    }
});
